// This file is automatically generated

import { DiagnosticSeverity } from "vscode";

// "Prescriptions" for Praat diagnostics
interface Praatscription {
    index: number, // Hardcoded index of this prescription
    name: string, // Name of this prescription
    ofMethod: string, // Name of the method this prescription is associated with
    severity: DiagnosticSeverity, // Severity of diagnostic
    mesage: string, // The message to be displayed to the user
}

interface PraatscriptionList {
    [index:number]: Praatscription
}

// List all available prescriptions
// export const prescriptionList: PraatscriptionList = {
    
// };